### ISSUE TITLE
建议nuxt，API可以从服务端请求

### ISSUE THREAD

**Issue by TsinghuaSIGS** [KeJunMao/ai-anything#13]

**Comment by KeJunMao** [comment]
作者没有钱钱，而免费云函数大多10s超时，所以就做成了客户端请求

**Comment by TsinghuaSIGS** [comment]
可以用vercel，很多程序都是托管在了vercel的，vercel可以免费托管，从vercel发起的api请求被封的概率也会小一些。
可以参考下面几个。
https://github.com/Yidadaa/ChatGPT-Next-Web
https://github.com/Chanzhaoyu/chatgpt-web
