### ISSUE TITLE
👍 功能最强的ChatGPT工具

### ISSUE THREAD

**Issue by 6drf21e** [KeJunMao/ai-anything#3]
推上过来的，是用过的功能最强的ChatGPT工具

就是有一点模板存放在localstorage里 ，做好的工具别人看不到。
不知道后续有没有存放在文件或者数据库的计划。

**Comment by KeJunMao** [comment]
在做了~

**Comment by KeJunMao** [comment]
现在可以先去Disussions里分享~

**Comment by KeJunMao** [comment]
@6drf21e 搞好了
